version: '3.9'

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "retaildb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - 5432:5432
